package com.harish.wordlookup.data

import android.content.ComponentName
import android.content.Context
import android.content.pm.PackageManager

/**
 * Switches which of the 26 per-language `activity-alias` components
 * (AndroidManifest.xml, `.ui.LauncherAlias<Code>`) is the enabled LAUNCHER
 * entry, so the home-screen icon carries the active language's own glyph.
 * Icons themselves are generated by tools/gen_lang_icons.py.
 *
 * This is a real, disclosed manifest-parity exception - see CLAUDE.md's
 * "Round 6" notes on why `manifest` isn't clean this round the way every
 * prior round kept it.
 */
class LauncherIcon(private val context: Context) {

    /**
     * Enables the alias for [languageName], disables the rest. Order matters:
     * the new alias is enabled *before* any other is disabled, so the device
     * is never observed with zero enabled LAUNCHER components - that state
     * would drop the app off the home screen with no way back in.
     */
    fun switchTo(languageName: String) {
        val pm = context.packageManager
        val target = Languages.get(languageName).code
        pm.setComponentEnabledSetting(
            aliasComponent(target),
            PackageManager.COMPONENT_ENABLED_STATE_ENABLED,
            PackageManager.DONT_KILL_APP,
        )
        for (language in Languages.ALL) {
            if (language.code == target) continue
            pm.setComponentEnabledSetting(
                aliasComponent(language.code),
                PackageManager.COMPONENT_ENABLED_STATE_DISABLED,
                PackageManager.DONT_KILL_APP,
            )
        }
    }

    private fun aliasComponent(code: String): ComponentName {
        val suffix = code.replaceFirstChar { it.uppercase() }
        return ComponentName(context, "com.harish.wordlookup.ui.LauncherAlias$suffix")
    }
}
